[package]
name = "knapsack"
version = "0.1.0"
edition = "2021"

[lib]
name = "knapsack"
path = "src/lib.rs"

[dependencies]
thiserror = "2.0.9"
text_io = "0.1.12"
clap = { version = "4.5.23", features = ["derive"] }
anyhow = "1.0.95"
